- name: Check if RescueTime was downloaded
  stat: path="{{ home_dir }}/rescuetime_current_amd64.deb"
  register: RescueTime

- name: Download RescueTime
  get_url:
    url: https://www.rescuetime.com/installers/rescuetime_current_amd64.deb
    dest: "{{ home_dir }}/rescuetime_current_amd64.deb"
  when: not RescueTime.stat.exists

- name: Install RescueTime
  command: "dpkg -i {{ home_dir }}/rescuetime_current_amd64.deb"
  when: RescueTime.stat.exists

- name: Remove RescueTime.deb
  file:
    path: "{{ home_dir }}/rescuetime_current_amd64.deb"
    state: absent