- name: Check if tmetric was downloaded
  stat: path="{{ home_dir }}/tmetric_desktop_amd64.deb"
  register: tmetric_check

- name: Download TMetric (time tracking)
  get_url:
    url: https://static.tmetric.com/desktop/download/linux/deb/amd64
    dest: "{{ home_dir }}/tmetric_desktop_amd64.deb"
  when: not tmetric_check.stat.exists

- name: Install TMetric
  command: "dpkg -i {{ home_dir }}/tmetric_desktop_amd64.deb"
  when: tmetric_check.stat.exists

- name: Remove tmetric_desktop_amd64.deb
  file:
    path: "{{ home_dir }}/tmetric_desktop_amd64.deb"
    state: absent


- name: Check if dropbox.tar.gz was downloaded
  stat: path="{{ home_dir }}/dropbox.tar.gz"
  register: dropbox_check

- name: Download dropbox.tar.gz
  tags: productivity
  get_url:
    url: https://www.dropbox.com/download?plat=lnx.x86_64
    dest: "{{ home_dir }}/dropbox.tar.gz"
  when: not dropbox_check.stat.exists

- name: Extract dropbox.tar.gz into ~/.dropbox-dist
  unarchive:
    src: "{{ home_dir }}/dropbox.tar.gz"
    dest: "{{ home_dir }}"
  when: dropbox_check.stat.exists

- name: Remove dropbox.tar.gz
  file:
    path: "{{ home_dir }}/dropbox.tar.gz"
    state: absent
  
- name: Install Dropbox integration for Nautilus
  tags: productivity
  apt:
    pkg: nautilus-dropbox
    state: latest
  
- name: Install Liferea (RSS reader)
  tags: productivity
  apt:
    pkg: liferea
    state: latest
