- name: Install FFmpeg
  snap:
    name: ffmpeg

- name: Install VLC
  snap:
    name: vlc

- name: Install youtube-dl
  snap:
    name: youtube-dl
    
- name: Install gallery-dl
  snap:
    name: gallery-dl