- name: Check if Minecraft was downloaded
  stat: path="{{ home_dir }}/Minecraft.deb"
  register: Minecraft

- name: Download Minecraft
  get_url:
    url: https://launcher.mojang.com/download/Minecraft.deb
    dest: "{{ home_dir }}/Minecraft.deb"
  when: not Minecraft.stat.exists

- name: Install Minecraft
  command: "dpkg -i {{ home_dir }}/Minecraft.deb"
  when: Minecraft.stat.exists

- name: Remove Minecraft.deb
  file:
    path: "{{ home_dir }}/Minecraft.deb"
    state: absent
