- name: Install a list of packages to their latest version
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - apt-transport-https
    - gnupg

- name: Enabling UFW, allowing all SSH
  community.general.ufw:
    state: enabled
    policy: deny
- name: Set logging
  community.general.ufw:
    logging: 'on'
- name: Allowing all access to port 22
  community.general.ufw:
    rule: allow
    port: '22'
    proto: tcp