- name: Check if nvm is installed (Node.js Version Manager)
  stat: path="{{ home_dir }}/.nvm"
  register: nvm_check

- name: Download nvm ({{ nvm.version }})
  get_url:
    url: https://raw.githubusercontent.com/creationix/nvm/{{ nvm.version }}/install.sh
    dest: "{{ home_dir }}/install_nvm.sh"
  when: not nvm_check.stat.exists
