---

- name: Download latest Miniconda for Linux 64 bit
  get_url:
    url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    dest: ./install_miniconda.sh

- name: Install (or update) Miniconda for Linux 64 bit
  shell: bash install_miniconda.sh -b -u
  notify:
    - Remove Miniconda installer

# - name: Install (or update) pipenv
#   shell: pip install --user --upgrade pipenv

# - name: Upgrade pip
#   shell: pip install --upgrade pip
