- name: Install pip for python 3
  apt:
    pkg:
        - python3-pip
        - python3-dev
    state: latest
    update_cache: yes

- name: Install virtualenv
  apt:
    pkg: virtualenv
    state: latest

- name: Install virtualenvwrapper
  apt:
    pkg: virtualenvwrapper
    state: latest

- name: Install pipenv
  command: "pip3 install --user pipenv"

- name: Check if miniconda dir is present in HOME
  stat: path="{{ home_dir }}/miniconda3"
  register: miniconda_dir_check

- name: Download latest Miniconda for Linux 64 bit
  get_url:
    url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    dest: ./Miniconda3-latest-Linux-x86_64.sh
  when: not miniconda_dir_check.stat.exists

- name: Install Jupyter notebook
  snap:
    name: jupyter
    channel: latest

- debug: msg="Run Miniconda3-latest-Linux-x86_64.sh to install Miniconda"

- debug: msg="Run `pip completion --bash >> ~/.bashrc` to have autocompletion with pip"

- debug: msg="Configure virtualenvwrapper if you want, or just use pipenv"
