- name: Install RClone
  apt:
    pkg: rclone
    state: latest

- name: Add Resilio signing key
  ansible.builtin.apt_key:
    url: "https://linux-packages.resilio.com/resilio-sync/key.asc"
    state: present
  
- name: Add Resilio Repo into sources list
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] http://linux-packages.resilio.com/resilio-sync/deb resilio-sync non-free
    state: present
    filename: resilio-sync
    
- name: Install resilio-sync
  ansible.builtin.apt:
   name: "resilio-sync"
   state: latest
   update_cache: true

- name: adding rslsync user to '"{{ lookup('env', 'USER') }}"' group
  user:
    name: 'rslsync'
    groups: "{{ lookup('env', 'USER') }}"
    append: yes

- name: Run a user service for resilio-sync
  ansible.builtin.systemd:
    enabled: yes
    name: resilio-sync
    state: started