- name: Install Skype
  snap:
    name: skype
    classic: yes

- name: Install Slack
  snap:
    name: slack
    classic: yes

- name: Install Telegram
  snap:
    name: telegram-desktop
    classic: yes
