- name: Install VS Code
  snap:
    name: code
    classic: yes

- name: Install Postman
  snap:
    name: postman
    channel: latest

- name: Install GIT
  apt:
    pkg: git
    state: latest

- name: Install DBeaver
  snap:
    name: dbeaver-ce
    channel: latest