---

- name: Install Visual Studio Code
  command: snap install vscode --classic

- name: Install PyCharm Community
  command: snap install pycharm-community --classic

- name: Install Postman
  command: snap install postman

- name: Install Insomnia
  command: snap install insomnia
