- name: Install Visual Studio Code (classic confinement)
  snap:
    name: code
    classic: yes

- name: Install PyCharm Community (classic confinement, latest/edge)
  snap:
    name: pycharm-community
    classic: yes
    channel: latest/edge

- name: Install Postman (REST API client)
  snap:
    name: postman
    channel: latest

- name: Install Insomnia (GraphQL API client)
  snap:
    name: insomnia
    channel: latest

- name: Install Byobu (shell multiplexer)
  apt:
    pkg: byobu
    state: latest

- name: Install Virtualbox (virtualization tool)
  apt:
    pkg: virtualbox
    state: latest

- name: Install Heroku CLI
  snap:
    name: heroku
    classic: yes
    channel: latest/stable