- name: Install Graphviz
  apt:
    pkg: graphviz
    state: latest

- name: Install Feh (Fast X11 image viewer)
  apt:
    pkg: feh
    state: latest

- name: Install Pinta (lightweight image drawing/editing)
  apt:
    pkg: pinta
    state: latest

# At the moment Gimp seems to have some issues with Flatpak. It IS installed,
# but it must be launched with: flatpak run org.gimp.GIMP//stable
# https://www.gimp.org/downloads/
# - name: Install gimp (using Flatpak)
#   shell: flatpak install https://flathub.org/repo/appstream/org.gimp.GIMP.flatpakref -y

- name: Add PPA required for Gimp
  apt_repository:
    repo: ppa:otto-kesselgulasch/gimp
    state: present

- name: Install Gimp (raster graphics editor)
  apt:
    pkg: gimp
    state: latest

- name: Install Inkscape (vector graphics editor)
  apt:
    pkg: inkscape
    state: latest

- name: Add PPA required for Peek
  apt_repository:
    repo: ppa:peek-developers/stable
    state: present

- name: Install Peek (GIF recorder)
  apt:
    pkg: peek
    state: latest

- name: Add PPA required for Shutter
  apt_repository:
    repo: ppa:linuxuprising/shutter
    state: present

- name: Install Shutter (screenshot tool)
  apt:
    pkg: shutter
    state: latest

- name: Install Blender (3D creation suite)
  apt:
    pkg: blender
    state: present