---

- name: Install Redis server
  apt:
    name: redis-server
    state: latest

- name: Install Redis Desktop Manager
  command: snap install redis-desktop-manager --classic

- name: Install pgAdmin and SQLite browser
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - pgadmin3
    - sqlitebrowser
