- name: Install Redis server
  apt:
    name: redis-server
    state: latest

- name: Install Redis Desktop Manager
  snap:
    name: redis-desktop-manager
    classic: yes

- name: Install pgAdmin and SQLite browser
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - pgadmin3
    - sqlitebrowser
