---

- name: Print out the hostname of target
  command: hostname

- name: Ensure that Aptitude repositories are up to date
  apt: update_cache=yes

- name: Install a list of packages to their latest version
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - chromium-browser
    - curl
    - git
    - git-cola
    - gitk
    - gparted
    - graphviz
    - grep
    - jq
    - less
    - libssl-dev
    - mc
    - silversearcher-ag
    - tldr
    - tree
    - vlc

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
