- name: Print out the hostname of target
  command: hostname

- name: Install a list of packages to their latest version
  tags: cli
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - bat
    - curl
    - direnv
    - grep
    - htop
    - jq
    - less
    - silversearcher-ag
    - tldr
    - trash-cli
    - tree

- name: Install Open SSL
  tags: security
  apt:
    pkg: libssl-dev
    state: latest

- name: Install Chromium
  tags: browser
  apt:
    pkg: chromium-browser
    state: latest

- name: Add PPA required for Firefox Nightly
  tags: browser
  apt_repository:
    repo: ppa:ubuntu-mozilla-daily/ppa
    state: present

- name: Install Firefox Nightly
  tags: browser
  apt:
    pkg: firefox-trunk
    state: latest

- name: Install ncdu (NCurses Disk Usage, replacement for du)
  tags: cli
  snap:
    name: ncdu

- name: Add PPA required for Flatpak
  tags: package-manager
  apt_repository:
    repo: ppa:alexlarsson/flatpak
    state: present

- name: Install Flatpak
  tags: package-manager
  apt:
    pkg: flatpak
    state: latest

- name: Install Vifm (File manager)
  tags: file-manager
  apt:
    pkg: vifm
    state: latest

- name: Upgrade installed packages
  tags: package-manager
  apt:
    upgrade: yes

- name: Remove useless packages from the cache
  tags: package-manager
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  tags: package-manager
  apt:
    autoremove: yes

- name: Download z (jump around the most frequently used directories)
  tags: cli
  get_url:
    url: https://raw.githubusercontent.com/rupa/z/master/z.sh
    dest: "{{ home_dir }}/bin/z.sh"
    mode: '777' # https://chmodcommand.com/chmod-777/

- debug: msg="fzf is available as apt package in Ubuntu 19.10"
