- name: Print out the hostname of target
  command: hostname

- name: Ensure that Aptitude repositories are up to date
  apt:
    update_cache: yes

- name: Install a list of packages to their latest version
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - chromium-browser
    - curl
    - direnv
    - gparted
    - graphviz
    - grep
    - htop
    - jq
    - less
    - libssl-dev
    - silversearcher-ag
    - tldr
    - tree
    - vlc

- name: Add PPA required for Flatpak
  apt_repository:
    repo: ppa:alexlarsson/flatpak
    state: present

- name: Install Flatpak
  apt:
    pkg: flatpak
    state: latest

- name: Add PPA required for Alacritty
  apt_repository:
    repo: ppa:mmstick76/alacritty
    state: present

- name: Install Alacritty (Terminal Emulator)
  apt:
    pkg: alacritty
    state: latest

- name: Install Vifm
  apt:
    pkg: vifm
    state: latest

- name: Upgrade installed packages
  apt:
    upgrade: yes

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- debug: msg="TODO - Install bat (https://github.com/sharkdp/bat)"
- debug: msg="TODO - Install fzf (https://github.com/junegunn/fzf)"
