- name: Install Stacer
  apt:
    pkg: stacer
    state: latest

- name: Install a list of packages to their latest version
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - curl
    - jq
    - yq
    - tldr
    - tree
    - net-tools
    - wget
    - glances
    - nmap

- name: Install ncdu (NCurses Disk Usage, replacement for du)
  snap:
    name: ncdu

- name: Gnome Tweaks
  apt:
    pkg: gnome-tweaks
    state: latest 
    
- name: Gnome Extensions
  apt:
    pkg: gnome-shell-extension-manager
    state: latest